# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn
      - yarn add nyc
  build:
    commands:
      - yarn test
      - aws cloudformation list-change-sets — stack-name lambda-unit-test
      - aws cloudformation package --template-file template.yaml --output-template-file cf-template.yaml --s3-bucket serverlesswithunittest

artifacts:
  files:
    - cf-template.yaml




